/*cremaos la base de datos con el nombre Inamhi*/
create database inamhi;
use inamhi

/*Tabla Regimen Laboral*/
CREATE TABLE regimen_laboral (
  codigo_regimen VARCHAR(10) PRIMARY KEY,
  nombre VARCHAR(100)
);

/*agregamos  datos proporcionados por la empresa a la tabla Regimen laboral */
INSERT INTO regimen_laboral (codigo_regimen, nombre) VALUES
('1', '1.SERVICIO CIVIL PUBLICO (LOSEP)'),
('2', '2.CODIGO DEL TRABAJO'),
('99', '99.JUBILADOS PATRONALES'),
('77', '77.PASIVOS');


/*Tabla estructura Programtica */
CREATE TABLE estructura_programatica (
  codigo_enlace VARCHAR(20) PRIMARY KEY,
  nombre VARCHAR(150)
);

/*Agregamos datos a la tabla  estructura Programatatica*/
INSERT INTO estructura_programatica (codigo_enlace, nombre)
VALUES
('1', '202542200000000010000000100051170000100000000'),
('2', '202542200000000550000100200071170020288888888'),
('3', '202542200000000010000000100058170000100000000');


/*Creamos la tabla Nivel Ocupacional*/
CREATE TABLE nivel_ocupacional (
  codigo_nivel VARCHAR(10) PRIMARY KEY,
  nombre VARCHAR(100)
);

/*Agregamos datos a la tabla nivel Ocupacional proporciaonado por la empresa */
INSERT INTO nivel_ocupacional (codigo_nivel, nombre) VALUES
('8', '8 NIVEL SUPERIOR DECRETO 624'),
('2', '2 NIVEL OPERATIVO'),
('1A', '1.CODIGO DE TRABAJO'),
('1B', '1 ESCALA JUBILADOS'),
('1C', '1 PASIVOS CORRIENTE'),
('2B', '2 PASIVOS INVERSION');

/*Creamos la tabla Modalidad laboral*/

CREATE TABLE modalidad_laboral (
  codigo_modalidad VARCHAR(10) PRIMARY KEY,
  nombre VARCHAR(100)
);

/*Agregamos datos a la tabla Modalidad laboral ,datos proporcionados por la empresa */
INSERT INTO modalidad_laboral (codigo_modalidad, nombre) VALUES
('1', 'NOMBRAMIENTO'),
('2', 'CONTRATOS OCASIONALES'),
('22', 'CONTRATO CODIGO TRABAJO INDEFINIDO'),
('27', 'PERSONAL JUBILADO');


/*Creamos la tabla Escala Ocupacional*/
CREATE TABLE escala_ocupacional (
  codigo_escala VARCHAR(10) PRIMARY KEY,
  nombre VARCHAR(100)
);

/*Agregamos datos a la tabla Escala Ocupacional , datos proporcionados por la empresa */
INSERT INTO escala_ocupacional (codigo_escala, nombre) VALUES
('NSD2', 'NIVEL JERARQUICO SUPERIOR 2 DEC. 601'),
('NSD3', 'NIVEL JERARQUICO SUPERIOR 3 DEC. 135'),
('NO03', 'SERVIDOR PUBLICO DE APOYO 1'),
('NO04', 'SERVIDOR PUBLICO DE APOYO 2'),
('NO05', 'SERVIDOR PUBLICO DE APOYO 3'),
('NO06', 'SERVIDOR PUBLICO DE APOYO 4'),
('NO07', 'SERVIDOR PUBLICO 1'),
('NO08', 'SERVIDOR PUBLICO 2'),
('NO09', 'SERVIDOR PUBLICO 3'),
('NO10', 'SERVIDOR PUBLICO 4'),
('NO11', 'SERVIDOR PUBLICO 5'),
('NO12', 'SERVIDOR PUBLICO 6'),
('NO13', 'SERVIDOR PUBLICO 7'),
('NO16', 'SERVIDOR PUBLICO 10'),
('CT3', 'NIVEL 3'),
('CT1', 'NIVEL 1'),
('JS2', 'JUBILADOS POR LEY'),
('PAS2', 'VALOR ASIGNAR PARA PAGO A TERCEROS (INVERSION)'),
('PAS1', 'VALOR ASIGNAR PARA PAGO A TERCEROS (CORRIENTE)');

/*cremaos la tabla Denominacion del Puesto*/
CREATE TABLE denominacion_puesto (
  codigo_denom VARCHAR(10) PRIMARY KEY,
  nombre VARCHAR(100)
);

/*Agregamos datos a la tabla denominacion del puesto,estos datos proporciono la empresa */
INSERT INTO denominacion_puesto (codigo_denom, nombre) VALUES
('AC2', 'ANALISTA DE CONTABILIDAD 1'),
('AC5', 'ANALISTA DE CONTABILIDAD 2'),
('AP5', 'ANALISTA DE PLANIFICACION 1'),
('ATTHH1', 'ANALISTA DE TALENTO HUMANO 1'),
('CO169', 'GUARDALMACEN'),
('CO2036', 'CHOFER'),
('CO2051', 'SECRETARIA'),
('CO61', 'OFICINISTA'),
('CO7', 'CONSERJE'),
('CONSEP-010', 'ANALISTA DE TICS 2'),
('CONSEP-011', 'ANALISTA 3 DE TALENTO HUMANO'),
('COV10', 'SERVIDOR PUBLICO 4'),
('COV4', 'SERVIDOR PUBLICO DE APOYO 2'),
('COV5', 'SERVIDOR PUBLICO DE APOYO 3'),
('DADFI', 'DIRECTOR ADMINISTRATIVO FINANCIERO'),
('DASJU', 'DIRECTOR DE ASESORIA JURIDICA'),
('DP100', 'ABOGADO 2'),
('DPLA', 'DIRECTOR DE PLANIFICACION'),
('HCN8', 'ESPECIALISTA 1'),
('INAMHI001', 'ASISTENTE DE PRONOSTICOS Y ALERTAS HIDROMETEOROLOGICAS'),
('INAMHI002', 'ASISTENTE EN GESTION DE LA RED DE OBSERVACION HIDROMETEOROLOGICA'),
('INAMHI005', 'DIRECTOR DE PRONOSTICO Y ALERTAS HIDROMETEREOLOGICOS'),
('INAMHI010', 'DIRECTOR DE LA RED NACIONAL DE OBSERVACION HIDROMETEOROLOGICA'),
('INAMHI013', 'ANALISTA EN GESTION DE LA RED DE OBSERVACION HIDROMETEOROLOGICA'),
('INAMHI014', 'ANALISTA EN CALIBRACION Y MANTENIMIENTO DE INSTRUMENTAL HIDROMETEORLOGICO'),
('INAMHI018', 'ESPECIALISTA EN GESTION DE LA INFORMACION HIDROMETEOROLOGICA 2'),
('INAMHI021', 'ANALISTA EN SISTEMAS INFORMATICOS HIDROMETEOROLOGICOS'),
('INAMHI025', 'ESPECIALISTA EN PRONOSTICOS Y ALERTAS HIDROMETEOROLOGICAS 2'),
('INAMHI026', 'ANALISTA EN PRONOSTICOS Y ALERTAS HIDROMETEOROLOGICAS'),
('INAMHI027', 'DIRECTOR DE ESTUDIOS INVESTIGACION Y DESARROLLO HIDROMETEOROLOGICO'),
('INAMHI029', 'ESPECIALISTA EN HIDROMETEOROLOGIA 2'),
('INAMHI031', 'ESPECIALISTA EN HIDROGEOLOGIA 2'),
('INAMHI033', 'ESPECIALISTA EN CLIMATOLOGIA 2'),
('INAMHI042', 'ANALISTA EN INNOVACION Y DESARROLLO TECNOLOGICO'),
('INAMHI046', 'ESPECIALISTA EN CALIDAD DE AGUA Y SEDIMENTOS 2'),
('INAMHI047', 'ANALISTA EN CALIDAD DE AGUA Y SEDIMENTOS'),
('INAMHI048', 'ASISTENTE DE AGUA Y SEDIMENTOS'),
('INAMHI050', 'ESPECIALISTA REGIONAL HIDROMETEOROLOGICO 3'),
('INAMHI051', 'ESPECIALISTA REGIONAL EN OPERACION Y MANTENIMIENTO DE LA RED DE OBSERVACION HIDROMETEOROLOGICA 2'),
('INAMHI052', 'ANALISTA REGIONAL EN OPERACION Y MANTENIMIENTO DE LA RED DE OBSERVACION HIDROMETEOROLOGICA'),
('INAMHI053', 'ESPECIALISTA REGIONAL EN LA GESTION PRIMARIA DE LA INFORMACION HIDROMETEOROLOGICA 2'),
('INAMHI055', 'ESPECIALISTA REGIONAL EN ESTUDIOS Y PRONOSTICOS HIDROMETEOROLOGICOS 3'),
('INAMHI057', 'ANALISTA REGIONAL EN ESTUDIOS Y PRONOSTICOS HIDROMETEOROLOGICOS'),
('INAMHI060', 'ASISTENTE EN CALIDAD DE AGUA Y SEDIMENTOS'),
('INIAP002', 'INVESTIGADOR AUXILIAR 1'),
('INIAP006', 'INVESTIGADOR AGREGADO 2'),
('INM001', 'ASISTENTE DE DOCUMENTACION Y ARCHIVO .'),
('INM002', 'ESPECIALISTA EN CALIDAD DE AGUA Y SEDIMENTOS 3'),
('INM003', 'TECNICO REGIONAL EN GESTION DE LA RED DE OBSERVACION HIDROMETEOROLOGICA'),
('INM004', 'TECNICO EN GESTION DE LA RED DE OBSERVACION HIDROMETEOROLOGICA'),
('INM005', 'ESPECIALISTA EN AGROMETEOROLOGIA 2'),
('JS2', 'JUBILADO POR LEY'),
('ME224', 'ANALISTA DE COMPRAS PUBLICAS 2'),
('ME228', 'ANALISTA DE PRESUPUESTO 2'),
('MF209', 'ANALISTA 1 DE ADMINISTRACION DE TALENTO HUMANO,'),
('MRE109', 'DIRECTOR/A DE ADMINISTRACION DE TALENTO HUMANO .'),
('NS3012', 'DIRECTOR EJECUTIVO'),
('PNG015', 'ASISTENTE CONTABILIDAD'),
('PROCU-074', 'ASISTENTE DE COMUNICACION SOCIAL'),
('PROCU-080', 'AUXILIAR DE SERVICIOS'),
('SGR031', 'ASISTENTE ADMINISTRATIVA'),
('TC62', 'TESORERO GENERAL'),
('UEP383', 'ANALISTA DE COMPRAS PUBLICAS');


/*Creamos la tabla empleados */
CREATE TABLE empleados (
  id INT AUTO_INCREMENT PRIMARY KEY,

  codigo_regimen VARCHAR(10),
  codigo_nivel VARCHAR(10),
  codigo_modalidad VARCHAR(10),
  codigo_escala VARCHAR(10),
  codigo_denom VARCHAR(10),
  codigo_enlace VARCHAR(20),

  fecha_inicio DATE,
  fecha_fin DATE,
  partida_individual VARCHAR(50),
  estado_puesto VARCHAR(50),
  grado VARCHAR(10),
  rmu_escala DECIMAL(10,2),
  rmu_puesto DECIMAL(10,2),
  rmu_sobrevalorado DECIMAL(10,2),

  ruc_patronal VARCHAR(20),
  codigo_sucursal VARCHAR(10),
  tipo_identificacion VARCHAR(20),
  numero_identificacion VARCHAR(30),
  nombres VARCHAR(200),
  apellidos VARCHAR(200), 

  provincia VARCHAR(100),
  canton VARCHAR(100),
  codigo_canton VARCHAR(10),

  codigo_puesto_adicional VARCHAR(10),
  puesto_adicional VARCHAR(100),
  codigo_unidad_organica VARCHAR(10),
  unidad_organica VARCHAR(100),

  aporte_individual DECIMAL(10,2),
  aporte_patronal DECIMAL(10,2),

  comision_servicios VARCHAR(10),
  estado_servidor VARCHAR(50),
  fondos_reserva VARCHAR(10),
  acumulacion_decimo_tercero VARCHAR(10),
  acumulacion_decimo_cuarto VARCHAR(10),

  -- Relaciones
  FOREIGN KEY (codigo_regimen) REFERENCES regimen_laboral(codigo_regimen),
  FOREIGN KEY (codigo_nivel) REFERENCES nivel_ocupacional(codigo_nivel),
  FOREIGN KEY (codigo_modalidad) REFERENCES modalidad_laboral(codigo_modalidad),
  FOREIGN KEY (codigo_escala) REFERENCES escala_ocupacional(codigo_escala),
  FOREIGN KEY (codigo_denom) REFERENCES denominacion_puesto(codigo_denom),
  FOREIGN KEY (codigo_enlace) REFERENCES estructura_programatica(codigo_enlace)
);
